spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    username: behdavar
    password: 123456
    url: jdbc:oracle:thin:@127.0.0.1:1521/XE
  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.Oracle12cDialect
      hibernate.format_sql: true
      hibernate.temp.use_jdbc_metadata_defaults: false
      hibernate.enable_lazy_load_no_trans: true